"""
FastAPI backend for the AI Travel Planning Assistant.

Exposes a single chat endpoint used by the React UI
(AITravelAgentUI/). Conversation history is kept in memory,
keyed by a session id generated by the frontend.
"""

import uuid

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from app.orchestrator import run_travel_assistant

app = FastAPI(title="AI Travel Planning Assistant API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory conversation store: session_id -> list of {role, content}.
# Cleared whenever the server restarts.
SESSIONS: dict[str, list[dict[str, str]]] = {}

MAX_HISTORY_TURNS = 10


class ChatRequest(BaseModel):
    message: str
    session_id: str | None = None


class ChatResponse(BaseModel):
    session_id: str
    answer: str
    sources: list[dict[str, str]]
    tools_used: list[str]


@app.get("/api/health")
def health_check():
    return {"status": "ok"}


@app.post("/api/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    message = request.message.strip()

    if not message:
        raise HTTPException(status_code=400, detail="Message must not be empty.")

    session_id = request.session_id or str(uuid.uuid4())
    history = SESSIONS.setdefault(session_id, [])

    result = await run_travel_assistant(message, history=history)

    history.append({"role": "user", "content": message})
    history.append({"role": "assistant", "content": result["answer"]})

    # Keep only the most recent turns so the prompt does not grow unbounded.
    if len(history) > MAX_HISTORY_TURNS * 2:
        del history[: -MAX_HISTORY_TURNS * 2]

    return ChatResponse(
        session_id=session_id,
        answer=result["answer"],
        sources=result["sources"],
        tools_used=result["tools_used"],
    )


@app.delete("/api/session/{session_id}")
def clear_session(session_id: str):
    SESSIONS.pop(session_id, None)
    return {"status": "cleared"}
