"""
FastAPI backend for the AI Travel Planning Assistant.

Exposes a single chat endpoint used by the React UI
(TravelAssistant.Client/). Conversation history is kept in memory,
keyed by a session id generated by the frontend.
"""

import json
import uuid

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from app.orchestrator import run_travel_assistant_stream

app = FastAPI(title="AI Travel Planning Assistant API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory conversation store: session_id -> list of {role, content}.
# Cleared whenever the server restarts.
SESSIONS: dict[str, list[dict[str, str]]] = {}

MAX_HISTORY_TURNS = 10


class ChatRequest(BaseModel):
    message: str
    session_id: str | None = None


@app.get("/api/health")
def health_check():
    return {"status": "ok"}


def _sse(payload: dict) -> str:
    return f"data: {json.dumps(payload)}\n\n"


@app.post("/api/chat")
async def chat(request: ChatRequest):
    message = request.message.strip()

    if not message:
        raise HTTPException(status_code=400, detail="Message must not be empty.")

    session_id = request.session_id or str(uuid.uuid4())
    history = SESSIONS.setdefault(session_id, [])

    async def event_stream():
        answer_parts: list[str] = []

        async for event in run_travel_assistant_stream(message, history=history):

            if event["type"] == "meta":
                yield _sse(
                    {
                        "type": "meta",
                        "session_id": session_id,
                        "sources": event["sources"],
                        "tools_used": event["tools_used"],
                    }
                )

            elif event["type"] == "chunk":
                answer_parts.append(event["text"])
                yield _sse({"type": "chunk", "text": event["text"]})

        answer = "".join(answer_parts)

        history.append({"role": "user", "content": message})
        history.append({"role": "assistant", "content": answer})

        # Keep only the most recent turns so the prompt does not grow unbounded.
        if len(history) > MAX_HISTORY_TURNS * 2:
            del history[: -MAX_HISTORY_TURNS * 2]

        yield _sse({"type": "done"})

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache"},
    )


@app.delete("/api/session/{session_id}")
def clear_session(session_id: str):
    SESSIONS.pop(session_id, None)
    return {"status": "cleared"}

